### ISSUE TITLE
[Support] Error installing wireguard-dkms on Raspberry Pi OS 64-bit, 5.4.79+ kernel

### ISSUE THREAD

**Issue by dragoselle** [pivpn/pivpn#1218]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue
I am trying to install PiVPN with Wireguard on **Raspbian 64-bit** for the first time and some of the kernel header files don't seem to exist, and it fails to install wireguard-dkms. I am on **kernel 5.4.79+**, and I get the following **output at installation**:

```
DKMS: install completed.
Building initial module for 5.10.4-v8+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
Building initial module for 5.4.79+
Error! Bad return status for module build on kernel: 5.4.79+ (aarch64)
Consult /var/lib/dkms/wireguard/1.0.20201221/build/make.log for more information.
dpkg: error processing package wireguard-dkms (--configure):
 installed wireguard-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 wireguard-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**OUTPUT in make.log:**
```

DKMS make.log for wireguard-1.0.20201221 for kernel 5.4.79+ (aarch64)
Wed Jan  6 20:03:03 GMT 2021
make: Entering directory '/usr/src/linux-headers-5.4.79+'
  AR      /var/lib/dkms/wireguard/1.0.20201221/build/built-in.a
  CC [M]  /var/lib/dkms/wireguard/1.0.20201221/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20201221/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20201221/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20201221/build/peer.o
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/wireguard/1.0.20201221/build/compat/compat.h:11,
                 from <command-line>:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:266: /var/lib/dkms/wireguard/1.0.20201221/build/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ./include/linux/types.h:6,
                 from /var/lib/dkms/wireguard/1.0.20201221/build/compat/compat.h:11,
                 from <command-line>:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>

```
I am kinda new at messing with kernels, looked through header directories and found an asm-generic directory, but no asm indeed. Tried reinstalling headers a couple of times with raspberry-kernel-headers and rpi-source as some people recommended on reddit posts but no success. Any help is appreciated.

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)
Did not find any relevant solutions, tried reinstalling headers, using rpi-source, no success

### Console output of      `curl -L install.pivpn.dev | bash`
```
  * Expire in 0 ms for 6 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 3 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 3 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 6 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 6 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 7 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 7 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 13 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 13 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 32 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 32 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 64 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 64 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
*   Trying 88.198.194.194...
* TCP_NODELAY set
* Expire in 149897 ms for 3 (transfer 0x55c9fc1c10)
* Expire in 200 ms for 4 (transfer 0x55c9fc1c10)
* Connected to install.pivpn.dev (88.198.194.194) port 80 (#0)
> GET / HTTP/1.1
> Host: install.pivpn.dev
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://install.pivpn.dev/
< Date: Wed, 06 Jan 2021 20:19:02 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< 
* Ignoring the response-body
{ [17 bytes data]
100    17  100    17    0     0     60      0 --:--:-- --:--:-- --:--:--    60
* Connection #0 to host install.pivpn.dev left intact
* Issue another request to this URL: 'https://install.pivpn.dev/'
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 0 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 1 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 2 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 3 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 3 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 5 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 5 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 4 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 6 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 6 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 7 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 7 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 8 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 10 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 16 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 14 ms for 1 (transfer 0x55c9fc1c10)
* Expire in 50 ms for 1 (transfer 0x55c9fc1c10)
*   Trying 88.198.194.195...
* TCP_NODELAY set
* Expire in 149972 ms for 3 (transfer 0x55c9fc1c10)
* Expire in 200 ms for 4 (transfer 0x55c9fc1c10)
* Connected to install.pivpn.dev (88.198.194.195) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: DEFAULT@SECLEVEL=1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS alert, internal error (592):
{ [2 bytes data]
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 1
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by orazioedoardo** [comment]
See: https://github.com/pivpn/pivpn/issues/1099#issuecomment-716382695

**Comment by dragoselle** [comment]
That simple? There's absolutely no workaround?

**Comment by orazioedoardo** [comment]
You could figure out what kernel headers are available in the repository that match your kernel version, install then manually, then skip the corresponding part of the script.

If you want a straightforward PiVPN installation on a 64-bit OS, use Ubuntu Server 20.04, which is supported.

**Comment by dragoselle** [comment]
I see. Thanks for the advice, will try Ubuntu Server for now.

**Comment by dragoselle** [comment]
Ubuntu Server 20.04 64bit worked flawlessly, thank you!
